### ISSUE TITLE
Mouse position application overlap text

### ISSUE THREAD

**Issue by ousudrs** [Bluegrams/MPos#4] opened 2021-11-05 10:44 UTC
New version 0.4 overlap text. Tested in multiple windows 10 machines.

![image]![Mouse_position](https://user-images.githubusercontent.com/20973473/140498691-6757972e-f261-4a71-9c85-d2c015efbcb3.jpg))

0.3 version works fine

**Comment by alxnull** [comment] 2022-04-08 16:43
Hey, thanks for reporting this issue. I'm currently trying to fix it and have uploaded a pre-release version with a patch at ~~https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable.zip/download~~ https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.5.0-Portable.zip/download. Would be glad if you could try that out and give feedback if it fixes the issue. Thanks!

[Also, this issue should be the same as others reported in #7]

**Comment by ousudrs** [comment] 2022-04-10 22:29
Hi @alxnull 
Thanks for fixing the issue. It's working now. 
I see the relative coordinates are not updating on existing windows. Not sure, if it's the intended way to work.

**Comment by alxnull** [comment] 2022-04-11 10:26
@ousudrs Great, thanks for testing!

> I see the relative coordinates are not updating on existing windows. Not sure, if it's the intended way to work.

I'm not sure I understand what you mean by this, could you maybe give an example?

**Comment by ousudrs** [comment] 2022-04-12 14:21
Start Windows Explorer(or any other application)
Start MPos
Check the relative coordinates when you mouse hover on the already existing windows explorer.
Now, open a new windows explorer(or any other application)
Check the relative coordinates when you mouse hover on the newly opened windows explorer(or any other application)

MPos failed to capture relative coordinates on existing windows. It worked fine if you open windows after starting MPos

**Comment by alxnull** [comment] 2022-04-12 21:27
@ousudrs Unfortunately, I'm unable to reproduce this on my side currently.

Maybe what you describe is related to the currently active window? MPos shows the position relative to the currently active window, i.e. if I want to have the position relative to a window that was opened before MPos itself, I have to click on the window again to set the focus to this window. Then, MPos will switch to showing positions relative to this window. At least this is how it is intended to work.

**Comment by ousudrs** [comment] 2022-04-13 09:59
Aha, sorry. It works as intended. I missed activating the window before checking the coordinates. Thank you

**Comment by alxnull** [comment] 2022-04-15 13:46
Closing with release of v.0.5

**Closed as completed by alxnull** 2022-04-15 13:46 UTC
Labels: bug
