### ISSUE TITLE
Corrupted layout when 4k screen is connected

### ISSUE THREAD

**Issue by holgerbrandl** [Bluegrams/MPos#7] opened 2022-01-07 20:50 UTC
For some reason, it has a corrupted size factor/layout, when starting the application while a 4k display is connected:

![image](https://user-images.githubusercontent.com/200952/148605568-d1f84104-5953-42d2-854a-7c7d44dbb659.png)

Used version: 0.4

**Comment by Crazypersonalph** [comment] 2022-01-25 05:10
Same, I have that problem as well

**Comment by rleyshon** [comment] 2022-02-11 09:01
I'm using the this workaround:
Open the exe properties and changing Compatibility > Change High DPI Settings
Override High DPI scaling behaviour - Ticked
Scaling performed by: System (Enhanced)

**Comment by alxnull** [comment] 2022-04-08 16:40
Hey all, thanks for bringing this up. I'm trying to fix this issue in-app and want to make sure everything works before I release an update. I have uploaded a preview version with a possible fix at ~~https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable.zip/download~~ https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.5.0-Portable.zip/download. Would be glad if you could try it out and give feedback if it fixes the problems. Thanks!

**Comment by Crazypersonalph** [comment] 2022-04-09 00:29
> Hey all, thanks for bringing this up. I'm trying to fix this issue in-app and want to make sure everything works before I release an update. I have uploaded a preview version with a possible fix at https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable.zip/download. Would be glad if you could try it out and give feedback if it fixes the problems. Thanks!

So I have taken a look at it, and it still seems broken. I have a 4K resolution display btw. There is no option for increasing the size of the box or decreasing. I can see it was made with C# and Powershell, but the TKinter GUI libraries with python might be able to help. I don't have that much expertise though 😅, so I might not be able to help, but somebody better than probably could.

**Comment by Crazypersonalph** [comment] 2022-04-09 00:36
> Hey all, thanks for bringing this up. I'm trying to fix this issue in-app and want to make sure everything works before I release an update. I have uploaded a preview version with a possible fix at https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable.zip/download. Would be glad if you could try it out and give feedback if it fixes the problems. Thanks!

Turning down the font size seemed to help somewhat, but some of the text is not inside the box

**Comment by alxnull** [comment] 2022-04-09 13:07
Thanks for testing @Crazypersonalph, let's have another try then: https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable-t2.zip/download.

There are some known issues with C#/ WinForms regarding high-DPI monitor support. Unfortunately, I don't have a 4k monitor myself, so some things are a bit difficult to test for me. Hope can take a look at the latest patch too, thanks!

**Comment by Crazypersonalph** [comment] 2022-04-09 14:00
> Thanks for testing @Crazypersonalph, let's have another try then: https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable-t2.zip/download.
> 
> There are some known issues with C#/ WinForms regarding high-DPI monitor support. Unfortunately, I don't have a 4k monitor myself, so some things are a bit difficult to test for me. Hope can take a look at the latest patch too, thanks!

The text is patched! There is one problem though, there is no options or view tab. (Those might not be the names, but I am talking about the grey tab at the top). Other than that, it looks good. I think re-scaling of the window would be a good feature to add in the future though

**Comment by Crazypersonalph** [comment] 2022-04-09 14:02
I think this issue can be marked closed and fixed now

**Comment by alxnull** [comment] 2022-04-09 14:52
> > Thanks for testing @Crazypersonalph, let's have another try then: https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable-t2.zip/download.
> > There are some known issues with C#/ WinForms regarding high-DPI monitor support. Unfortunately, I don't have a 4k monitor myself, so some things are a bit difficult to test for me. Hope can take a look at the latest patch too, thanks!
> 
> The text is patched! There is one problem though, there is no options or view tab. (Those might not be the names, but I am talking about the grey tab at the top). Other than that, it looks good. I think re-scaling of the window would be a good feature to add in the future though

Great!
What do you mean by "there is no options or view tab"? Is the menu bar at the top not shown correctly or not shown at all? Does it change anything if you hide and un-hide the menu (using the `Alt` key or via "Show Menu Bar" in the context menu)?

**Comment by Crazypersonalph** [comment] 2022-04-09 23:47
> > > Thanks for testing @Crazypersonalph, let's have another try then: https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.4.1-Portable-t2.zip/download.
> > > There are some known issues with C#/ WinForms regarding high-DPI monitor support. Unfortunately, I don't have a 4k monitor myself, so some things are a bit difficult to test for me. Hope can take a look at the latest patch too, thanks!
> > 
> > 
> > The text is patched! There is one problem though, there is no options or view tab. (Those might not be the names, but I am talking about the grey tab at the top). Other than that, it looks good. I think re-scaling of the window would be a good feature to add in the future though
> 
> Great! What do you mean by "there is no options or view tab"? Is the menu bar at the top not shown correctly or not shown at all? Does it change anything if you hide and un-hide the menu (using the `Alt` key or via "Show Menu Bar" in the context menu)?

The menu bar at the top is not shown at all. There is only the stop button. The Alt button doesn't do anything but remove the stop button.

**Comment by alxnull** [comment] 2022-04-10 12:54
Couldn't figure out the cause for the issue with the menu bar. I'll remove the menu bar in the next version anyway. Thanks again for your help on this @Crazypersonalph!

(Final preview version now at Final test version is now at https://sourceforge.net/projects/mpos/files/pre-release/MPos-v.0.5.0-Portable.zip/download).

**Comment by alxnull** [comment] 2022-04-15 13:46
Closing with v.0.5.

**Closed as completed by alxnull** 2022-04-15 13:46 UTC
Labels: bug
